config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"


  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get 'users/current' => 'users#current'
  get 'users/distance' => 'users#distance', as: 'distance'
  get 'users/popularity' => 'users#popularity', as: 'popularity'

 

  resources :users do
    resources :skills
     resources :reviews
    resources :skills do
      resources :requests
    end
  end

  resources :requests do
    resources :messages
  end

  

  resources :skills
  resources :categories
  resources :collections
  resources :requests 
  resources :search


 

end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user 
	belongs_to :request 

	# validates :user, :request, :content, {presence: true}
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	before_action :authenticate_user!

	def new
		@message = Message.new
		respond_to  do |format|
			format.html
			format.json { render json: @message }
			format.js
		end
	end


	def create
		@request = Request.find(params[:request_id])
		@new_message = @request.messages.new(message_params)
		@new_message.user = current_user
		if @new_message.save
			respond_to do |format|
			format.js
      format.html { redirect_to request_path(@request), notice: 'Message was sent successfully' }
		end
		else
			flash[:notice] = "something went wrong"
			render :'messages/new'
		end
	end

	def show
		@request = Request.find(params[:id])
		@messages = @request.messages
		render :'messages/show'
	end

	private

	def message_params
		params.require(:message).permit(:content,:request_id)
	end
	
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= bootstrap_form_for(:message, url: request_messages_path, remote: true, id: "new-form-message")do |f| %>
<p>
	<%=f.label :content %>
	<%=f.text_field :content %>
	<p>
		<%=f.submit "Submit" %>
	 <% end %> 
	</p>

app/views/messages/_message.html.erb
	 <p><%=message.user.first_name%></p>
  <p><%= message.content %></p>
  <p><%=time_ago_in_words(message.created_at) %> ago</p>

 

app/views/messages/create.js.erb
$('#new_message').remove();
$("new-form-message").show();
 $('#messages').append('<%= j render("message", :message => @new_message) %>');
 $('#messages').hide();

app/views/messages/new.html.erb
<div id="the-basics">
  <input class="typeahead" type="text" placeholder="States of USA">
</div>

app/views/messages/new.js.erb
$("#new-message").hide().after('<%= j render("form")%>');

app/views/messages/show.html.erb
<div id="messages">
  <% @messages.each do |message| %>
	<p><%=message.content %></p>
  	
  <% end %>
</div>