config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"


  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get 'users/current' => 'users#current'
  get 'users/distance' => 'users#distance', as: 'distance'
  get 'users/popularity' => 'users#popularity', as: 'popularity'

 

  resources :users do
    resources :skills
     resources :reviews
    resources :skills do
      resources :requests
    end
  end

  resources :requests do
    resources :messages
  end

  

  resources :skills
  resources :categories
  resources :collections
  resources :requests 
  resources :search


 

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :sent_requests, class_name: "Request", foreign_key: :sender_id
	has_many :received_requests, class_name: "Request", foreign_key: :receiver_id
	has_many :written_reviews, class_name: "Review", foreign_key: :sender_id
	has_many :received_reviews, class_name: "Review", foreign_key: :receiver_id
	has_many :collections, foreign_key: :teacher_id
	has_many :skills, through: :collections
	has_many :messages
	has_many :categories, through: :skills

	validates :first_name, :last_name, :email, :password_digest, :city, :state, :zip, :st_num, :st_name, presence: true
	validates :email, uniqueness: true
  validates :zip, :length => { :is => 5 }
  validates :zip, :st_num, :numericality => { :only_integer => true }
	#validates :first_name, :last_name, :city, :state, :st_name, presence: true

	has_secure_password

	def full_name
		"#{self.first_name} #{self.last_name}"
	end

	def city_state
		"#{self.city}, #{self.state}"
	end


	def distance(current_user)
		distance = Geocoder::Calculations.distance_between([current_user.latitude, current_user.longitude], [self.latitude, self.longitude])
		distance.round(1)
	end



 	def address
		[st_num, st_name, city, state, zip].compact.join(' ')
	end

	geocoded_by :address
	after_validation :geocode

	# Return a valid gravatar URL
	# default image rating is set to "g"
	# default image size is set to 200x200 px
	# if user does not have gravatar account, return a random "retro" gravatar
	def create_gravatar_url
		"http://www.gravatar.com/avatar/#{md5_hash_email(self.email)}?r=g&s=200&d=retro"
	end

	private
	# Return an md5 hash for a given email
	def md5_hash_email(email)
		Digest::MD5.hexdigest(email.strip.downcase)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!, except: [:new, :create]


	def index
		@categories = Category.all
		@users = User.all.select { |num|  num != current_user  } 
		
		if request.xhr?
			respond_to do |format|
        		format.json { render json: @users }
        	end
    	end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(users_params)
		@user.avatar = @user.create_gravatar_url
		respond_to do |format|
			if @user.save
				session[:user_id] = @user.id
				format.html { redirect_to @user, notice: 'user was successfully created.' }
				# format.json { render :show, status: :created, user: @user }
			else
				format.html { render :new }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
 	end

 	def show
 	 @request = Request.new
 		puts "params[:id]: #{params[:id]}"
 		@user = User.find(params[:id])
 		"test"
 	end

 	def edit
 		@user = User.find(params[:id])
 		if current_user == @user
 			render :'users/edit'
 		else
 			render text: "Couldn't find what you were looking for", status: 404
 		end
 	end

 	def update
 		@user = User.find(params[:id])
 		if current_user == @user
	 		@user.assign_attributes(users_params)
	 		if @user.save
	 			redirect_to user_path(@user)
	 		else
	 			@errors = @user.errors.full_messages
 			end
 		else
 			render text: "Couldn't find what you were looking for", status: 404
 		end
 	end

 	def current
 		@current = current_user 
 		if request.xhr?
      		respond_to do |format|
        		format.json { render "users/current.json" }
      		end
    	end
 	end

 	def distance
 		@users = User.all.sort_by {|a| a.distance(current_user)}.select { |num|  num != current_user  } 	
		@categories = Category.all
		if request.xhr?
      		respond_to do |format|
        		format.json { render "users/distance.json" }
      		end
    	end
 	end

	def popularity
		@users = User.all.sort_by {|a| a.received_reviews.count}.select { |num|  num != current_user  }.reverse	
		@categories = Category.all
		if request.xhr?
      		respond_to do |format|
        		format.json { render "users/popularity.json" }
      		end
    	end
 	end

	private

	def users_params
		params.require(:user).permit(:first_name,:last_name,:email, :password,:city, :state, :zip,:st_num, :st_name, :occupation, :education,:description )
	end
end

app/views/users/_categories.html.erb
<div class="categories">
  <!-- <div class="btn-group"> -->
    <% @categories.each do |category| %>
    <button type="button" class="btn btn-primary btn-lg" aria-haspopup="true" aria-expanded="false">
    <%= link_to category.name, category, class: "cat ", id:"#{category.id}" %>
    </button>
  <% end %>
<!--    </div> -->
  <ul>
<!--  <p class="gr">Categories: </p> -->
  
  </ul>
<!-- </div> -->
  <br>
  <div class="left">
    <br>
    <p class="gr">Sort by: <%= link_to 'Distance', distance_path, id:'distance' %> |
    <%= link_to 'Popularity', popularity_path, id:'popularity' %></p>
  </div>
    <br>
    <br>
    <br>
    <p class="gr  left mini-m">Search by: </p>
    <%= form_tag search_index_path,  class: 'search', id: 'search-form', :method => :get do %>
      <div id="city">
        <%= text_field_tag :city,  params[:city], :placeholder => 'City', class: "form-control medium typeahead"%>
      </div>
      <div id="the-basics">
        <%= text_field_tag :search, params[:search], :placeholder => 'Skill',  class: "form-control medium typeahead"%>
      </div>
          <%= submit_tag "search", :name => nil, class: "btn btn-default " %>
    <% end %>
    <div id="message"><br><center><p class="red"><em>No results found</em></p><center></div>
    </div>
 

app/views/users/_error.html.erb
<div class="boxes" style='width: 800px;'>
  <div  style='width: 800px; height: 400px;'>
  <center>
<h1>We could not find anybody in that location!</h1></center> </div>
</div>

app/views/users/_map.html.erb
<!-- <div id="outDIV" style="position:fixed; top:0">
  <div id="inDIV" style="width:50%; height:100%"> -->
    <div id="map-canvas" style="width: 100%; height: 850px">
  <div id="map"></div>
</div>
<!--   </div>
</div> -->


<%= current_user.id %>
<script type="text/javascript">
var myMarkers = [];
var initialLocation;
var info = <%= raw @hash.to_json %>
var current = <%= raw @home.to_json %>
var map;
function initMap() {
  	map = new google.maps.Map(document.getElementById('map'), {
    zoom: 12
  });
  if(navigator.geolocation) {
    browserSupportFlag = true;
    navigator.geolocation.getCurrentPosition(function(position) {
      initialLocation = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
      map.setCenter(initialLocation);
    }, function() {
      handleNoGeolocation(browserSupportFlag);
    });
  }
  // Browser doesn't support Geolocation
  else {
    browserSupportFlag = false;
    handleNoGeolocation(browserSupportFlag);
  }

  function handleNoGeolocation(errorFlag) {
    if (errorFlag == true) {
      alert("Geolocation service failed.");
      initialLocation = newyork;
    } else {
      alert("Your browser doesn't support geolocation. We've placed you in Siberia.");
      initialLocation = siberia;
    }
    map.setCenter(initialLocation);
  }  

  //setMarkers();
}

function placeDBMarker(pinData, avatar) {
  var infowindow;
   var id = pinData.id.toString();
    $('#profile'+id).show();


  function attachSecretMessage(marker, secretMessage) {
    infowindow = new google.maps.InfoWindow({
    content: secretMessage
    });
  }
  var id = pinData.id.toString();
  if (avatar==null) {
    avatar = {
      url: pinData.avatar,
      size: new google.maps.Size(71, 71),
      origin: new google.maps.Point(0, 0),
      anchor: new google.maps.Point(17, 34),
      scaledSize: new google.maps.Size(50, 50)
    }; 
  } 

  var pinLatlng = new google.maps.LatLng(pinData.latitude, pinData.longitude);
  var marker = new google.maps.Marker({
    position: pinLatlng, 
    customInfo: id, 
    icon: avatar,
    map: map});

  attachSecretMessage(marker, marker['customInfo']);
  myMarkers.push(marker);

  google.maps.event.addListener(marker, 'click', function() {
    $('.profile').hide();
    $('#profile'+infowindow.content).show();
    console.log(infowindow.content)
  });


}



$(document).ready(function() {
  $('#message').hide();
  var getAjax = $.get('/users.json', "json");
  getAjax.done(function(response)
    {
      // console.log(response)
      for (var i = 0; i < response.length; i ++){
       placeDBMarker(response[i]);
      }
  });
  var getUser = $.get('/users/current.json', "json");
  getUser.done(function(response){  
    var image = '/home.png';
    placeDBMarker(response, image);
  });

  $(document).on("click", "#home", function(event) {
    event.preventDefault();
    
    var getAjax = $.get('/users.json', "json");
      getAjax.done(function(response)
      {
        // console.log(response)
        for (var i = 0; i < response.length; i ++){
         placeDBMarker(response[i]);
        }
    });
    var getUser = $.get('/users/current.json', "json");
    getUser.done(function(response){  
      var image = '/home.png';
      placeDBMarker(response, image);
    });
  });

  $(document).on("click", ".cat", function(event) {
    event.preventDefault();
    deleteMarkers();
    var id = $(this).attr('id');
    var url = '/categories/'+ id +'.json'
    var getUsersByCategory = $.get(url, "json");
    getUsersByCategory.done(function(response){  
      var image = '/home.png';
      console.log(response)
      if(response.length > 0) {
        $('.profile').hide();
        for (var i = 0; i < response.length; i ++){
          placeDBMarker(response[i]);
          
          $('#profile'+response[i].id).show();
        }
      } else {
      $('.profile').hide();
      }
    });
    var getUser = $.get('/users/current.json', "json");
    getUser.done(function(response){  
      var image = '/home.png';
      placeDBMarker(response, image);
    });
  });
   $(document).on("submit", "#search-form", function(event){
    event.preventDefault();
    deleteMarkers();
    // console.log(this);
    var getUser = $.get('/users/current.json', "json");
    getUser.done(function(response){  
      var image = '/home.png';
      placeDBMarker(response, image);
    });

    var data = $(this).serialize();
    // console.log(data)
    var request = $.ajax({
      url: '/search',
      method: "post",
      data: data
    }).done(function(response){  
      if(response.length > 0) {
        $('.profile').hide();

        for (var i = 0; i < response.length; i ++){
          placeDBMarker(response[i]);
          
          $('#profile'+response[i].id).show();
        }
      } else {
      $('.profile').hide();
      $('#message').fadeIn( "slow" ).fadeOut( "slow" );;
      }
    });
  });
   $(document).on("click", "#popularity", function(event) {
    event.preventDefault();
    var divs =  $('.profile');
    $('.profile').remove();
    divs.sort(function (b,a) {
      var aCount = parseInt($(a).attr('data-reviews'));
      var bCount = parseInt($(b).attr('data-reviews'));
      console.log(aCount)
      if (aCount > bCount) {
        return 1;
      }
      if (aCount < bCount)  {
        return -1;
      };
      return 0;
    });
   $('#mini-profiles').append(divs);

  });
    // var getUser = $.get('/users/current.json', "json");
    // getUser.done(function(response){  
    //   var image = '/home.png';
    //   placeDBMarker(response, image);
    // });

    $(document).on("click", "#distance", function(event) {
    event.preventDefault();
    var divs =  $('.profile');
    $('.profile').remove();
    divs.sort(function (a,b) {
      aCount = parseFloat($(a).attr('data-distance'));
      bCount = parseFloat($(b).attr('data-distance'));
      console.log(aCount)
      if (aCount > bCount) {
        return 1;
      }
      if (aCount < bCount)  {
        return -1;
      };
      return 0;
    });
   $('#mini-profiles').append(divs);
 });
  

  function setMapOnAll(map) {
    for (var i = 0; i < myMarkers.length; i++) {
      myMarkers[i].setMap(map);
    }
  }
  function clearMarkers() {
    setMapOnAll(null);
  }
  function deleteMarkers() {
    clearMarkers();
    myMarkers = [];
  }


});
  






</script>


<script async defer
      src="https://maps.googleapis.com/maps/api/js?&key=&callback=initMap">
</script>

app/views/users/_mini_profiles.html.erb
<div class="mini"  id="mini-profiles">
  <% @users.each do |user| %>
  <% next if user.id == user_id %>
    <div class="profile boxes" id="profile<%= user.id %>" data-reviews="<%= user.received_reviews.count %>"  data-distance="<%= user.distance(current_user) %>">
      <div class="left">
      <center>
        <img class="avatar" src="<%= user.avatar %>" alt="profile-picture" >
      </center>
      <%= link_to user.first_name, user, class:"yellow" %>
      </div>
      <div class="right">
      <p class="green"><i class="fa fa-home"></i>lives 
      <%= user.distance(current_user) %> miles from you </p>
       <p> <i class="fa fa-star-o"></i> had 
       <%= user.received_reviews.count %>
       recieved reviews </p>
      
       
        <p class="ye"> <i class="fa fa-usd"> </i>
        <% if user.collections[0] != nil %>
       <%= user.collections[0].hourly_rate %>
       <% else %>
        0 
       <% end %>
        per hour</p>
       
       </div>
      <br>
      <i class="fa fa-fort-awesome"></i>
      <ul class="center">
        <li><b>SKILLS:</b></li>
        <% user.skills.uniq.each do |skill| %>
          <li><%= skill.name %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/users/_tag.html.erb
<%= link_to user.first_name, user %>

app/views/users/edit.html.erb
<h1>Edit your information and click "Update" to save</h1>

<%=bootstrap_form_for @user,method: :put do |f| %>
  <div class="col-2">
    <label>
      <%=f.number_field :st_num %>
    </label>
  </div>
   <div class="col-2">
    <label>
      <%=f.text_field :st_name %>
    </label>
  </div>
   <div class="col-2">
    <label>
      <%=f.text_field :city %>
    </label>
  </div>
   <div class="col-2">
    <label>
      <%=f.text_field :state %>
    </label>
  </div>
  <div class="col-2">
    <label>
     <%=f.number_field :zip %>
    </label>
  </div>
   <div class="col-2">
    <label>
     <%=f.text_field :description %>
    </label>
  </div>
  <div class="col-2">
    <label>
     <%=f.text_field :occupation %>
    </label>
  </div>
  <div class="col-2">
    <label>
     <%=f.text_field :education %>
    </label>
  </div>
     <%if @errors %>
      <%@errors %>
    <% end %>
    <div class="col-submit">
      <%=f.submit "Update"%>
    </div>
  <% end %>
  <div>

app/views/users/index.html.erb
<div class="row">
	<div class="col-md-6 main">
		<% if @users != nil && @users %>
			<%= render 'users/map' %>
		<% else %>
			<%= render 'users/error' %>
	<% end %>
	</div>
	<div class="col-md-6 main">
		<%= render 'users/categories' %>
		<%= render 'users/mini_profiles' %>
	</div>

</div>

app/views/users/new.html.erb
<%=bootstrap_form_for(@user) do |f| %>
  <div class="col-2">
    <label>
      <%=f.text_field :first_name %>
    </label>
  </div>
  <div class="col-2">
    <label>
      <%=f.text_field :last_name %>
    </label>
  </div>
  <div class="col-3">
    <label>
     <%=f.text_field :email %>
    </label>
  </div>
  <div class="col-3">
    <label>
	    <%=f.password_field :password %>
    </label>
  </div>
  <div class="col-3">
  	<label>
     	<%=f.text_field :st_num %>
    </label>
  </div>
   <div class="col-2">
    <label>
      <%=f.text_field :st_name %>
    </label>
  </div>
   <div class="col-2">
    <label>
  		<%=f.text_field :city %>
    </label>
  </div>
   <div class="col-2">
    <label>
      <%=f.text_field :state %>
    </label>
  </div> <div class="col-2">
    <label>
     <%=f.text_field :zip %>
    </label>
     </div> <div class="col-3">
    <label>
     <%=f.text_field :occupation %>
    </label>
     </div> <div class="col-3">
    <label>
     <%=f.text_field :education %>
    </label>
     </div> <div class="col-3">
    <label>
     <%=f.text_field :description %>
    </label>
  </div>
  <div>
  <%=f.hidden_field :longitude %>
	<%=f.hidden_field :latitude %>
  </div>
  <%if @errors %>
		<%@errors %>
	<% end %>
  <div class="col-submit">
    <%=f.submit "Register"%>
  </div>
  <% end %>

app/views/users/show.html.erb
<main class="mediums">
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-3">
			<div id="profile-pic-box">
				<header>
					<br>
					<br>
  				<br>
	  			<br>
				<img src="<%= @user.avatar %>" alt="profile-picture">
				<br>
				<br>
					<div class="boxes left bl">
		    			<p><b>Occupation </b> <%= @user.occupation %></p>
						<p><b>Education </b> <%= @user.education.capitalize %></p>
		    			<p><b>Bio </b> <%= @user.description %></p>
		    			<% if current_user == @user %>
		    				<br>
		    				<%= link_to 'Edit', edit_user_path(@user), class:'right' %>
		    			<% end %>
		    		</div>
				</header>
			</div> 
		</div> 
		<div class="col-md-6">
  		<br>
  		<br>
  		<br>
			<h1><%= @user.full_name %></h1>
			<h3><%= @user.city_state %></h3>
			<% if current_user == @user %>
  				<%= link_to "Edit your profile", edit_user_path %>
  			<% end %>
	  		<br>
	  		<br>
	  		<br>
		  <div class="tab-content">
		    <div role="tabpanel" class="tab-pane fade in active" id="skills">
					<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
			    	<% @user.collections.each do |collection| %>
			    		<div class="panel panel-default"> 
							<div class="panel-heading aqq" role="tab" id="collection-<%= collection.id %>">
								<h4 class="panel-title"><%= collection.skill.name %></h4>
					    		<% if current_user && user_id != @user.id  %>
      		    			<em>Want to learn this skill from <%= @user.first_name %>? Send a message to start coordinating!</em>
					 					<%= bootstrap_form_for @request, layout: :inline, as: :request, url: user_skill_requests_path(@user, collection.skill_id), method: "post" do |f| %>
									    <%= f.text_field :content, hide_label: true, placeholder: "Write a message here" %>
								    	<%= f.submit "Request a lesson!", class: "btn btn-success" %>
										<% end %>
							    <% end %>
      		    		<% if current_user == @user %>
										<%= link_to "Edit Skill", edit_collection_path(collection), method: "get" %> |
		    						<%= link_to "Delete", collection_path(collection), method: "delete", data: { confirm: "Click OK to delete this skill." } %>
	    						<% end %>
	    						<div class="panel-body">
					      	<% @collection = collection %>
					      	<%= render 'collections/details', locals: { collection: @collection }  %>
      		    		<br>
      		    		<br>
      		    	</div>
			    		</div>
						</div>
    				<% end %>
					</div>
		    </div>
	  		<h3>Reviews:</h3>
	  			<% if  @user.received_reviews[0]  %>
				    <%@user.received_reviews.each do |review| %>
				      <div class="boxes cn hon">
					    	<img class="right" width="60" height="60" src="<%=review.sender.avatar %>" >
					    	<br>
					    	<p class="left gr"><%=review.sender.first_name %><br><em><%=time_ago_in_words(review.created_at) %><em></p>
					    	<br>
					     	<p class="padd"><%=review.content %></p>
					     	<p class="right"></p>
					     	<hr>
					    </div>
			     	<% end %>
			    <% else %>
			    	<br>
			     	<p><em>No reviews recieved</em></p>
			    <% end %>
			  </div>
			</div>
		<div class="col-md-1"></div>
	</div>
</main>