config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"


  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get 'users/current' => 'users#current'
  get 'users/distance' => 'users#distance', as: 'distance'
  get 'users/popularity' => 'users#popularity', as: 'popularity'

 

  resources :users do
    resources :skills
     resources :reviews
    resources :skills do
      resources :requests
    end
  end

  resources :requests do
    resources :messages
  end

  

  resources :skills
  resources :categories
  resources :collections
  resources :requests 
  resources :search


 

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "Skillo", root_path, class: "navbar-brand" %>
      <!-- <a class="navbar-brand" href="#">SKILLO</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
    
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", users_path %></li>
        <%if current_user %>
            <li><%= link_to "Profile", current_user %></li>
            <% if !unread_messages %>
                <li><a href="<%= requests_path%>"><i class="fa fa-envelope-o"></i></a></li>
            <% else %>
                  <li  ><a href="<%= requests_path%>"> <i class="fa fa-envelope-o"> <%= count_messages %></i></a></li>
            <% end %> 
             <li><%= link_to "Logout", logout_path %></li>
        <%else%>
            <li>
                <a href="/login" data-toggle="modal" data-target="#login-modal">Login</a>
            </li>
            <li>
                <%= link_to "Register", new_user_path %>
            </li>
        <% end %> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>


<!-- 
Navigation
    <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
            <li class="sidebar-brand">
                <%= link_to "Skillo", root_path %>
            </li>
            <li>
                <%= link_to "Home", users_path %>
            </li>
           
            <% if current_user %> 
            
      
            <% if !unread_messages %>
                  <li><a href="<%= requests_path%>"><i class="fa fa-envelope-o"></i></a></li>
            <% else %>
                  <li  ><a href="<%= requests_path%>"> <i class="fa fa-envelope-o"> <%= count_messages %></i></a></li>
            <% end %>
           
            
            <li><%= link_to "Edit Skills", new_user_skill_path(user_id) %></li>

            <li><%= link_to "Logout", logout_path %></li>
            <%else%>
            <li>
                <a href="/login" data-toggle="modal" data-target="#login-modal">Login</a>
            </li>
            <li>
                <%= link_to "Register", new_user_path %>
            </li>
            <%end%>
        </ul>
        </ul>
        </ul>
    </nav>
 -->
    
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
          <div class="modal-dialog">
                <div class="loginmodal-container">
                    <h1>Login to Your Account</h1><br> 
                    <%= bootstrap_form_tag(url:"/login",method: "post") do |f| %>
                    <center>
                        <%= f.email_field :email, placeholder: "email" %>
                        <%= f.password_field :password, placeholder: "password"%>
                        <%= f.submit "Login" %>
                    </center>
                    <% end %>   
                  <div class="login-help">
                    <a href="/signup"><h4>Register</h4></a>
                    </div>
                </div>

            </div>
            </div>
            <br>

            <%= @error %>

    

    <!-- Custom Theme JavaScript -->
    <script>
    // Closes the sidebar menu
    $("#menu-close").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });

    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });

    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    </script>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>SKILLO</title>
	<%= render 'layouts/scripts' %>
	<%= csrf_meta_tags %>
	<%= javascript_include_tag 'application' %>
	<%= stylesheet_link_tag    'application', media: 'all'%>
	<%= csrf_meta_tags %>
	</head>
	<body>
				
		
			<%= render 'layouts/navigation' %>
		
			<%= yield %>
		
	</body>
	
</html>